BASE=../../../..

LIBAMF_OBJS=libamf/src/amf0.o libamf/src/hash.o libamf/src/io.o libamf/src/ptrarray.o libamf/src/types.o
LOCAL_OBJS=rtmp_sig.o rtmp.o rtmp_tcp.o $(LIBAMF_OBJS)
LOCAL_CFLAGS=-Ilibamf/src

include $(BASE)/build/modmake.rules
