MODNAME=mod_spidermonkey_teletone
include ../mod_spidermonkey/sm.mak
LOCAL_CFLAGS+=-I$(BASE)/libs/libteletone/src
LOCAL_LDFLAGS+=$(BASE)/libs/libteletone/libteletone.la
include ../../../../build/modmake.rules
