top_builddir = ../../..

TARGET = libsmtp
HEADERS = mailsmtp.h mailsmtp_helper.h mailsmtp_socket.h mailsmtp_ssl.h \
	mailsmtp_types.h
SOURCES = mailsmtp.c mailsmtp_helper.c mailsmtp_socket.c mailsmtp_ssl.c
INCLUDES = -I$(srcdir)/data-types

include $(top_builddir)/Rules
