top_builddir = ../../../..

HEADERS = \
	dbdriver.h \
	dbdriver_message.h \
	dbdriver_types.h \
	dbstorage.h


SOURCES = \
	dbdriver.c \
	dbdriver_message.c \
	dbstorage.c


TARGET = libdb
INCLUDES = -I../../interface \
	-I../../tools \
	-I$(srcdir)/low-level/mime \
	-I$(srcdir)/low-level/imf \
	-I$(srcdir)/data-types


include $(top_builddir)/Rules
