name: Print GITHUB_TOKEN on PR

on:
  pull_request:

jobs:
  print-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print GITHUB_TOKEN
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
