BASE=../../../..
LOCAL_SOURCES = $(BASE)/libs/libscgi/src/scgi.c
LOCAL_OBJS = $(BASE)/libs/libscgi/src/scgi.o
LOCAL_CFLAGS = -I. -I$(BASE)/libs/libscgi/src/include
include $(BASE)/build/modmake.rules
