<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="speexdsp-version.props" Condition=" '$(speexdspVersionImported)' == '' "/>
    <Import Project="downloadpackage.task" Condition=" '$(downloadpackagetask_Imported)' == '' " />
  </ImportGroup>
  <PropertyGroup>
    <downloadspeexdspPropsImported>true</downloadspeexdspPropsImported>
  </PropertyGroup>

  <!--
       Download Target.
       Name must be unique.
       By design, targets are executed only once per project.

       Usage:

       package: URI

       expectfileordirectory: Skips the download and extraction if exists

       outputfolder: Folder to store a downloaded file.
                     By default "$(BaseDir)libs", if empty

       outputfilename: If not empty, overrides filename from URI.
                       .exe files don't get extracted

       extractto: Folder to extract an archive to
   -->

  <Target Name="speexdspDownloadTarget" BeforeTargets="CustomBuild;PreBuildEvent;" DependsOnTargets="7za">
      <DownloadPackageTask
           package="https://github.com/xiph/speexdsp/archive/refs/tags/SpeexDSP-$(speexdspVersion).tar.gz"
           expectfileordirectory="$(BaseDir)libs\speexdsp-$(speexdspVersion)\libspeexdsp\resample.c"
           outputfolder=""
           outputfilename="speexdsp-$(speexdspVersion).tar.gz"
           extractto="$(BaseDir)libs\"
           moveafter="speexdsp-SpeexDSP-$(speexdspVersion)|speexdsp-$(speexdspVersion)"
      />
  </Target>

</Project>
