<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="ldns-version.props" Condition=" '$(ldnsVersionImported)' == '' "/>
    <Import Project="downloadpackage.task" Condition=" '$(downloadpackagetask_Imported)' == '' " />
  </ImportGroup>
  <PropertyGroup Label="UserMacros">
    <ldnsLibDir>$(BaseDir)libs\ldns-$(ldnsVersion)_$(ldnsBuildNumber)</ldnsLibDir>
  </PropertyGroup>

  <!--
       Download Target.
       Name must be unique.
       By design, targets are executed only once per project.

       Usage:

       package: URI

       expectfileordirectory: Skips the download and extraction if exists

       outputfolder: Folder to store a downloaded file.
                     By default "$(BaseDir)libs", if empty

       outputfilename: If not empty, overrides filename from URI.
                       .exe files don't get extracted

       extractto: Folder to extract an archive to
   -->

  <Target Name="ldnsBinariesDownloadTarget" BeforeTargets="CustomBuild" DependsOnTargets="7za">
      <DownloadPackageTask
           package="https://github.com/freeswitch/windows-deps/releases/download/ldns-v$(ldnsVersion)_$(ldnsBuildNumber)/ldns-$(ldnsVersion)_$(ldnsBuildNumber)-binaries-$(Platform.ToLower())-$(Configuration.ToLower()).zip"
           expectfileordirectory="$(ldnsLibDir)\binaries\$(Platform)\$(Configuration)\ldns.lib"
           outputfolder=""
           outputfilename=""
           extractto="$(BaseDir)libs\"
      />
  </Target>
  <Target Name="ldnsHeadersDownloadTarget" BeforeTargets="CustomBuild" DependsOnTargets="7za">
      <DownloadPackageTask
           package="https://github.com/freeswitch/windows-deps/releases/download/ldns-v$(ldnsVersion)_$(ldnsBuildNumber)/ldns-$(ldnsVersion)_$(ldnsBuildNumber)-headers.zip"
           expectfileordirectory="$(ldnsLibDir)\include\ldns\ldns.h"
           outputfolder=""
           outputfilename=""
           extractto="$(BaseDir)libs\"
      />
  </Target>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(ldnsLibDir)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(ldnsLibDir)\binaries\$(Platform)\$(Configuration);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>ldns.lib;ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
