<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <libjpegVersion>10</libjpegVersion>
    <libjpegBuildNumber>1</libjpegBuildNumber>
  </PropertyGroup>
  <PropertyGroup>
    <libjpegVersionImported>true</libjpegVersionImported>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="libjpegVersion">
      <Value>$(libjpegVersion)</Value>
    </BuildMacro>
    <BuildMacro Include="libjpegBuildNumber">
      <Value>$(libjpegBuildNumber)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
