<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="libshout-version.props" Condition=" '$(libshoutVersionImported)' == '' "/>
    <!-- libshout.lib refers to both of these; a consumer links them through here. -->
    <Import Project="ogg.props" Condition=" '$(OggVersionImported)' == '' "/>
    <Import Project="pthreads.props" Condition=" '$(PthreadsVersionImported)' == '' "/>
    <Import Project="downloadpackage.task" Condition=" '$(downloadpackagetask_Imported)' == '' " />
  </ImportGroup>
  <PropertyGroup Label="UserMacros">
    <libshoutLibDir>$(BaseDir)libs\libshout-$(libshoutVersion)_$(libshoutBuildNumber)</libshoutLibDir>
  </PropertyGroup>

  <!--
       Download Target.
       Name must be unique.
       By design, targets are executed only once per project.

       Usage:

       package: URI

       expectfileordirectory: Skips the download and extraction if exists

       outputfolder: Folder to store a downloaded file.
                     By default "$(BaseDir)libs", if empty

       outputfilename: If not empty, overrides filename from URI.
                       .exe files don't get extracted

       extractto: Folder to extract an archive to
   -->

  <Target Name="libshoutBinariesDownloadTarget" BeforeTargets="CustomBuild" DependsOnTargets="7za">
      <DownloadPackageTask
           package="https://github.com/freeswitch/windows-deps/releases/download/libshout-v$(libshoutVersion)_$(libshoutBuildNumber)/libshout-$(libshoutVersion)_$(libshoutBuildNumber)-binaries-$(Platform.ToLower())-$(Configuration.ToLower()).zip"
           expectfileordirectory="$(libshoutLibDir)\binaries\$(Platform)\$(Configuration)\libshout.lib"
           outputfolder=""
           outputfilename=""
           extractto="$(BaseDir)libs\"
      />
  </Target>
  <Target Name="libshoutHeadersDownloadTarget" BeforeTargets="CustomBuild" DependsOnTargets="7za">
      <DownloadPackageTask
           package="https://github.com/freeswitch/windows-deps/releases/download/libshout-v$(libshoutVersion)_$(libshoutBuildNumber)/libshout-$(libshoutVersion)_$(libshoutBuildNumber)-headers.zip"
           expectfileordirectory="$(libshoutLibDir)\include\shout\shout.h"
           outputfolder=""
           outputfilename=""
           extractto="$(BaseDir)libs\"
      />
  </Target>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(libshoutLibDir)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(libshoutLibDir)\binaries\$(Platform)\$(Configuration);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>libshout.lib;ws2_32.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>
