<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <OggVersion>1.3.6</OggVersion>
    <OggBuildNumber>1</OggBuildNumber>
  </PropertyGroup>
  <PropertyGroup>
    <OggVersionImported>true</OggVersionImported>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="OggVersion">
      <Value>$(OggVersion)</Value>
    </BuildMacro>
    <BuildMacro Include="OggBuildNumber">
      <Value>$(OggBuildNumber)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
