<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <PthreadsVersion>2.9.1</PthreadsVersion>
    <PthreadsBuildNumber>1</PthreadsBuildNumber>
  </PropertyGroup>
  <PropertyGroup>
    <PthreadsVersionImported>true</PthreadsVersionImported>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="PthreadsVersion">
      <Value>$(PthreadsVersion)</Value>
    </BuildMacro>
    <BuildMacro Include="PthreadsBuildNumber">
      <Value>$(PthreadsBuildNumber)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
