<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="basedir.props" Condition=" '$(BaseDirImported)' == ''"/>
  </ImportGroup>
  <PropertyGroup Label="UserMacros">
    <speexdspVersion>1.2.1</speexdspVersion>
  </PropertyGroup>
  <PropertyGroup>
    <speexdspVersionImported>true</speexdspVersionImported>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="speexdspVersion">
      <Value>$(speexdspVersion)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
