<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
    <Import Project="sphinxbase-version.props" Condition=" '$(sphinxbaseVersionImported)' == '' "/>
  </ImportGroup>

  <PropertyGroup Label="UserMacros">
    <sphinxbase_libDir>$(BaseDir)libs\sphinxbase-$(sphinxbaseVersion)</sphinxbase_libDir>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(sphinxbase_libDir)\include\win32;$(sphinxbase_libDir)\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>

</Project>
