/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.35
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace FreeSWITCH.Native {

public enum switch_rtp_crypto_key_type_t {
  NO_CRYPTO,
  AES_CM_128_HMAC_SHA1_80,
  AES_CM_128_HMAC_SHA1_32
}

}
