/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.36
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace FreeSWITCH.Native {

[System.Flags] public enum switch_channel_flag_enum_t {
  CF_ANSWERED = (1 << 0),
  CF_OUTBOUND = (1 << 1),
  CF_EARLY_MEDIA = (1 << 2),
  CF_ORIGINATOR = (1 << 3),
  CF_TRANSFER = (1 << 4),
  CF_ACCEPT_CNG = (1 << 5),
  CF_WAIT_FOR_ME = (1 << 6),
  CF_BRIDGED = (1 << 7),
  CF_HOLD = (1 << 8),
  CF_SERVICE = (1 << 9),
  CF_TAGGED = (1 << 10),
  CF_WINNER = (1 << 11),
  CF_CONTROLLED = (1 << 12),
  CF_PROXY_MODE = (1 << 13),
  CF_SUSPEND = (1 << 14),
  CF_EVENT_PARSE = (1 << 15),
  CF_REPEAT_STATE = (1 << 16),
  CF_GEN_RINGBACK = (1 << 17),
  CF_RING_READY = (1 << 18),
  CF_BREAK = (1 << 19),
  CF_BROADCAST = (1 << 20),
  CF_UNICAST = (1 << 21),
  CF_VIDEO = (1 << 22),
  CF_EVENT_LOCK = (1 << 23),
  CF_RESET = (1 << 24),
  CF_ORIGINATING = (1 << 25),
  CF_STOP_BROADCAST = (1 << 26),
  CF_PROXY_MEDIA = (1 << 27),
  CF_INNER_BRIDGE = (1 << 28),
  CF_REQ_MEDIA = (1 << 29)
}

}
