.TH ldns-verifyzone 1 "27 May 2008"
.SH NAME
ldns-verify-zone \- read a DNSSEC signed zone and verify it.
.SH SYNOPSIS
.B ldns-verify-zone 
.IR ZONEFILE 

.SH DESCRIPTION

\fBldns-verify-zone\fR reads a DNS zone file and verifies it. 

RRSIG resource records are checked against the DNSKEY set at the zone apex.

Each name is checked for an NSEC(3), if appropriate.

.SH OPTIONS
.TP
.TP
\fB-h\fR
Show usage and exit

.TP
\fB-v\fR
Show the version and exit

.TP
\fB-V\fR \fInumber\fR
Set the verbosity level (default 3):

 0: Be silent
 1: Print result, and any errors
 2: Same as 1 for now
 3: Print result, any errors, and the names that are
    being checked
 4: Same as 3 for now
 5: Print the zone after it has been read, the result, 
    any errors, and the names that are being checked


.SH AUTHOR
Written by the ldns team as an example for ldns usage.

.SH REPORTING BUGS
Report bugs to <ldns-team@nlnetlabs.nl>. 

.SH COPYRIGHT
Copyright (C) 2008 NLnet Labs. This is free software. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.
