//speechrecog
RECOGNITION-COMPLETE 543257 COMPLETE MRCP/1.0
Completion-Cause:000 success
Waveform-URL:http://web.media.com/session123/audio.wav
Content-Type:application/x-nlsml
Content-Length:446

  <?xml version="1.0"?>
  <result x-model="http://IdentityModel"
    xmlns:xf="http://www.w3.org/2000/xforms"
    grammar="session:request1@form-level.store">
      <interpretation>
          <xf:instance name="Person">
              <Person>
                  <Name> Andre Roy </Name>
              </Person>
          </xf:instance>
                    <input>   may I speak to Andre Roy </input>
      </interpretation>
  </result>