#!/usr/bin/env python3
"""Generate files.ts for AgentBox deployment from Sphinx build output.

Walks the _build/site/ directory, base64-encodes every file, and writes
a TypeScript module that maps URL paths to Uint8Array content.

Usage:
    python3 scripts/gen_agentbox_files.py [--site-dir _build/site] [--out functions/<project>-doc/files.ts]
"""

import argparse
import base64
import os
import sys

SKIP_DIRS = {".doctrees", "_sources"}
SKIP_FILES = {".buildinfo", "objects.inv"}
SKIP_EXTENSIONS = {".pyc", ".pyo", ".map"}
# Static assets are identical across language builds; keep only /en/_static/
# and let index.ts rewrite /zh/_static/* -> /en/_static/*
DEDUP_STATIC_PREFIXES = {"zh/_static", "zh/_sphinx_design_static"}
MAX_FILE_SIZE = 2 * 1024 * 1024  # 2 MB per file


def should_skip(rel_path: str) -> bool:
    parts = rel_path.split(os.sep)
    for part in parts:
        if part in SKIP_DIRS or part.startswith("."):
            return True
    basename = os.path.basename(rel_path)
    if basename in SKIP_FILES:
        return True
    _, ext = os.path.splitext(rel_path)
    if ext in SKIP_EXTENSIONS:
        return True
    norm = rel_path.replace(os.sep, "/")
    for prefix in DEDUP_STATIC_PREFIXES:
        if norm.startswith(prefix):
            return True
    return False


def collect_files(site_dir: str) -> dict[str, bytes]:
    entries: dict[str, bytes] = {}
    for root, _dirs, files in os.walk(site_dir):
        for fname in sorted(files):
            fpath = os.path.join(root, fname)
            rel = os.path.relpath(fpath, site_dir)
            if should_skip(rel):
                continue
            size = os.path.getsize(fpath)
            if size > MAX_FILE_SIZE:
                print(f"  SKIP (too large): /{rel} ({size} bytes)", file=sys.stderr)
                continue
            with open(fpath, "rb") as f:
                data = f.read()
            url_path = "/" + rel.replace(os.sep, "/")
            entries[url_path] = data
    return entries


def write_ts(entries: dict[str, bytes], out_path: str) -> None:
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("// Auto-generated by scripts/gen_agentbox_files.py — do not edit\n")
        f.write("// Embedded static files for AgentBox deployment\n\n")
        f.write("function decode(b64: string): Uint8Array {\n")
        f.write("  const bin = atob(b64);\n")
        f.write("  const arr = new Uint8Array(bin.length);\n")
        f.write("  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);\n")
        f.write("  return arr;\n")
        f.write("}\n\n")
        f.write("export const FILES: Record<string, Uint8Array> = {\n")
        for path in sorted(entries.keys()):
            b64 = base64.b64encode(entries[path]).decode("ascii")
            f.write(f'  "{path}": decode("{b64}"),\n')
        f.write("};\n")

    total_size = os.path.getsize(out_path)
    print(f"Generated {out_path}")
    print(f"  {len(entries)} files embedded, {total_size / 1024 / 1024:.1f} MB total")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--site-dir",
        default="_build/site",
        help="Sphinx bilingual build output directory (default: _build/site)",
    )
    parser.add_argument(
        "--out",
        default="functions/doc/files.ts",
        help="Output TypeScript file path",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.site_dir):
        print(f"Error: site directory not found: {args.site_dir}", file=sys.stderr)
        print("Run 'make html-all' first to build the bilingual site.", file=sys.stderr)
        sys.exit(1)

    print(f"Scanning {args.site_dir} ...")
    entries = collect_files(args.site_dir)
    if not entries:
        print("Error: no files found to embed.", file=sys.stderr)
        sys.exit(1)

    write_ts(entries, args.out)


if __name__ == "__main__":
    main()
