top_builddir = ../../..

TARGET = libimf
HEADERS = mailimf.h mailimf_types.h mailimf_write_file.h \
	mailimf_types_helper.h \
	mailimf_write_generic.h mailimf_write_mem.h
SOURCES = mailimf.c mailimf_types.c mailimf_write_file.c \
	mailimf_types_helper.c \
	mailimf_write_generic.c mailimf_write_mem.c
INCLUDES = -I$(srcdir)/data-types

include $(top_builddir)/Rules
