.TH "FREESWITCH" "1" "October 10, 2007" "" ""
.nh
.ad l
.SH "NAME"
freeswitch \- Open Source telephony platform
.SH "SYNOPSIS"
.HP 7
\fBfreeswitch\fR [\fIoption\fR...]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBfreeswitch\fR
command.
.PP
This manual page was written for the
Debian
distribution because we're too lame to write a real manual page. But we have a superb website over here:
.UR http://www.freeswitch.org/
.BR http://www.freeswitch.org/
.SH "SEE ALSO"
.PP
\fBundocumented\fR(7).
