BASE=../../../..
include $(BASE)/build/modmake.rules

LOCAL_CFLAGS=-I/usr/local/lib/erlang/lib/erl_interface-3.5.8/include -L/usr/local/lib/erlang/lib/erl_interface-3.5.8/lib/ -D_REENTRANT
LOCAL_LDFLAGS=-lei
