BASE=../../../..
LOCAL_SOURCES=handle_msg.c ei_helpers.c
LOCAL_OBJS=handle_msg.o ei_helpers.o
include $(BASE)/build/modmake.rules


LOCAL_CFLAGS=-I/usr/local/lib/erlang/lib/erl_interface-3.5.9/include -L/usr/local/lib/erlang/lib/erl_interface-3.5.9/lib/ -D_REENTRANT
LOCAL_LDFLAGS=-lei
