.TH JS-CONFIG 1 "22 July 2006"
.SH NAME
.BR js-config " - Mozilla JavaScript C API Configuration Query Utility"
.SH SYNOPSIS
.B js-config
.RB [ --help ]
.RB [ --version ]
.RB [ --prefix ]
.RB [ --exec-prefix ]
.RB [ --bindir ]
.RB [ --libdir ]
.RB [ --includedir ]
.RB [ --mandir ]
.RB [ --datadir ]
.RB [ --acdir ]
.RB [ --cppflags ]
.RB [ --cflags ]
.RB [ --ldflags ]
.RB [ --libs ]
.SH DESCRIPTION
The Mozilla JavaScript C API Configuration Query Utility
.B js-config
is a command line utility
for querying various build-time parameters when
linking the
.B Mozilla JavaScript
language engine ("SpiderMonkey"),
as provided by the
.B OSSP js
distribution, into own applications.
.PP
For platforms where
.BR pkg-config ( 1 )
is available one can use this as an alternative, too.
The advantage of
.BR js-config ( 1 )
is that it is a stand-alone shell script without
any dependencies and already ships with the
.B OSSP js
distribution.
.SH EXAMPLES
.RS 0
cc `js-config --cppflags` -o foo foo.c `js-config --ldflags --libs`
.RE
.SH SEE ALSO
.BR js ( 1 ),
.BR js ( 3 )
.PP
.RS 0
http://www.mozilla.org/js/spidermonkey/
.RE
.RS 0
http://www.ossp.org/pkg/lib/js/
.RE
.SH AUTHOR
The author of the 
.B Mozilla JavaScript
language implementation ("SpiderMonkey") is
.I Brendan Eich
from the 
.IR "Mozilla Foundation" .
This manual page was written by 
.I Ralf S. Engelschall
for the 
.B OSSP js
distribution of 
.BR "Mozilla JavaScript" .
