.TH JS 3 "22 July 2006"
.SH NAME
.BR libjs " - Mozilla JavaScript C API"
.SH SYNOPSIS
.RS 0
.B cc `js-config --cppflags` -o foo foo.c `js-config --ldflags --libs`
.RE
.RS 0
.B cc `pkg-config --cflags js` -o foo foo.c `pkg-config --libs js`
.RE
.SH DESCRIPTION
The Mozilla JavaScript C API
is the programmatic interface to the 
.B Mozilla JavaScript
language engine ("SpiderMonkey").
For the complete reference documentation of the Mozilla JavaScript C API please see
the following online documents:
.TP 8
.I JS Embedder's Guide
http://www.mozilla.org/js/spidermonkey/apidoc/jsguide.html
.TP 8
.I JS Embedder's Reference
http://www.mozilla.org/js/spidermonkey/apidoc/complete-frameset.html
.SH SEE ALSO
.BR js-config ( 1 ),
.BR js ( 1 )
.PP
.RS 0
http://www.mozilla.org/js/spidermonkey/
.RE
.RS 0
http://www.ossp.org/pkg/lib/js/
.RE
.SH AUTHOR
The author of the 
.B Mozilla JavaScript
language implementation ("SpiderMonkey") is
.I Brendan Eich
from the 
.IR "Mozilla Foundation" .
This manual page was written by 
.I Ralf S. Engelschall
for the 
.B OSSP js
distribution of 
.BR "Mozilla JavaScript" .
