##
##  OSSP uuid - Universally Unique Identifier
##  Copyright (c) 2004-2007 Ralf S. Engelschall <rse@engelschall.com>
##  Copyright (c) 2004-2007 The OSSP Project <http://www.ossp.org/>
##
##  This file is part of OSSP uuid, a library for the generation
##  of UUIDs which can found at http://www.ossp.org/pkg/lib/uuid/
##
##  Permission to use, copy, modify, and distribute this software for
##  any purpose with or without fee is hereby granted, provided that
##  the above copyright notice and this permission notice appear in all
##  copies.
##
##  THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
##  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
##  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
##  IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
##  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
##  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
##  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
##  USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
##  ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
##  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
##  OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
##  SUCH DAMAGE.
##
##  uuid_compat.pod: Data::UUID Backward Compatibility Perl API (Perl/POD part)
##

=pod

=head1 NAME

Data::UUID - B<OSSP uuid> Backward Compatibility Perl Binding

=head1 DESCRIPTION

B<Data::UUID> is the B<OSSP uuid> backward compatibility Perl binding
to the API of the original B<Data::UUID> module. It allows other
B<Data::UUID> based Perl modules to run with B<OSSP::uuid> without
changes.

=head1 SEE ALSO

B<OSSP::uuid>.

=head1 HISTORY

The backward compatibility Perl binding B<Data::UUID> for B<OSSP
uuid> was originally implemented in 2004 by Piotr Roszatycki
E<lt>dexter@debian.orgE<gt>. It was later cleaned up and speed optimized
in December 2005 by David Wheeler E<lt>david@justatheory.comE<gt>.

=cut

