BASE=../../../..
LOCAL_SOURCES=$(MODDIR)/expreval.c $(MODDIR)/exprinit.c $(MODDIR)/exprobj.c $(MODDIR)/exprutil.c $(MODDIR)/exprfunc.c $(MODDIR)/exprmem.c $(MODDIR)/exprpars.c $(MODDIR)/exprval.c
LOCAL_OBJS=$(MODDIR)/expreval.o $(MODDIR)/exprinit.o $(MODDIR)/exprobj.o $(MODDIR)/exprutil.o $(MODDIR)/exprfunc.o $(MODDIR)/exprmem.o $(MODDIR)/exprpars.o $(MODDIR)/exprval.o
LOCAL_LDFLAGS=-lm
include $(BASE)/build/modmake.rules

