#! /bin/sh
#
# Run the sdp tests
#
# usage: run_test_sdp [test_program] [test-directory]
#

test_sdp="${1:-./test_sdp}"
tests="${2:-tests}"

if test -r $tests/message-1.sdp ; then

for n in 1 2 3 4 5 6 7 8 9 10;
do 
    echo -n "$n: "
    "$test_sdp" < "$tests/message-$n.sdp" && echo OK
done

else 
    echo "sdp run-tests: no tests found, skipping."
fi

