top_builddir = ../../../..

HEADERS = \
		mime_message_driver.h


SOURCES = \
		mime_message_driver.c


TARGET = libmime-message
INCLUDES = -I../../interface -I$(srcdir)/data-types

include $(top_builddir)/Rules
