' <auto-generated/>
#Const $NamespaceDefine$ = 1
#Const $MetadataDefine$ = 1

#If ADDMETADATA
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.IsDirty", Global.RootNamespace.ThisAssembly.Git.IsDirtyString)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.Branch", Global.RootNamespace.ThisAssembly.Git.Branch)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.Commit", Global.RootNamespace.ThisAssembly.Git.Commit)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.Sha", Global.RootNamespace.ThisAssembly.Git.Sha)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Major", Global.RootNamespace.ThisAssembly.Git.BaseVersion.Major)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Minor", Global.RootNamespace.ThisAssembly.Git.BaseVersion.Minor)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseVersion.Patch", Global.RootNamespace.ThisAssembly.Git.BaseVersion.Patch)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.Commits", Global.RootNamespace.ThisAssembly.Git.Commits)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.Tag", Global.RootNamespace.ThisAssembly.Git.Tag)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.BaseTag", Global.RootNamespace.ThisAssembly.Git.BaseTag)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Major", Global.RootNamespace.ThisAssembly.Git.SemVer.Major)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Minor", Global.RootNamespace.ThisAssembly.Git.SemVer.Minor)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Patch", Global.RootNamespace.ThisAssembly.Git.SemVer.Patch)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Label", Global.RootNamespace.ThisAssembly.Git.SemVer.Label)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.DashLabel", Global.RootNamespace.ThisAssembly.Git.SemVer.DashLabel)>
<Assembly: System.Reflection.AssemblyMetadata("GitInfo.SemVer.Source", Global.RootNamespace.ThisAssembly.Git.SemVer.Source)>
#End If

#If LOCALNAMESPACE
Namespace Global._RootNamespace_
#Else
Namespace Global
#End If
    ''' <summary>Provides access to the git information for the current assembly.</summary>
    Partial Class ThisAssembly
        ''' <summary>Provides access to the git information for the current assembly.</summary>
        Partial Public Class Git
            ''' <summary>IsDirty: $GitIsDirty$</summary>
            Public Const IsDirty As Boolean = $GitIsDirty$

            ''' <summary>IsDirtyString: $GitIsDirty$</summary>
            Public Const IsDirtyString As String = "$GitIsDirty$"

            ''' <summary>Branch: $GitBranch$</summary>
            Public Const Branch As String = "$GitBranch$"

            ''' <summary>Commit: $GitCommit$</summary>
            Public Const Commit As String = "$GitCommit$"

            ''' <summary>Commit: $GitSha$</summary>
            Public Const Sha As String = "$GitSha$"

            ''' <summary>Commits on top of base version: $GitCommits$</summary>
            Public Const Commits As String = "$GitCommits$"

            ''' <summary>Tag: $GitTag$</summary>
            Public Const Tag As String = "$GitTag$"

            ''' <summary>Base tag: $GitBaseTag$</summary>
            Public Const BaseTag As String = "$GitBaseTag$"

            ''' <summary>Provides access to the base version information used to determine the <see cref="SemVer" />.</summary>
            Partial Public Class BaseVersion
                ''' <summary>Major: $GitBaseVersionMajor$</summary>
                Public Const Major As String = "$GitBaseVersionMajor$"
           
              ''' <summary>Minor $GitBaseVersionMinor$</summary>
              Public Const Minor As String = "$GitBaseVersionMinor$"
           
              ''' <summary>Patch $GitBaseVersionPatch$</summary>
              Public Const Patch As String = "$GitBaseVersionPatch$"
            End Class

            ''' <summary>Provides access to SemVer information for the current assembly.</summary>
            Partial Public Class SemVer
                ''' <summary>Major: $GitSemVerMajor$</summary>
                Public Const Major As String = "$GitSemVerMajor$"

                ''' <summary>Minor: $GitSemVerMinor$</summary>
                Public Const Minor As String = "$GitSemVerMinor$"

                ''' <summary>Patch: $GitSemVerPatch$</summary>
                Public Const Patch As String = "$GitSemVerPatch$"

                ''' <summary>Label: $GitSemVerLabel$</summary>
                Public Const Label As String = "$GitSemVerLabel$"

                ''' <summary>Label with dash prefix: $GitSemVerDashLabel$</summary>
                Public Const DashLabel As String = "$GitSemVerDashLabel$"

                ''' <summary>Label with dash prefix: $GitSemVerSource$</summary>
                Public Const Source As String = "$GitSemVerVerSource$"
            End Class
        End Class
    End Class
End Namespace
