MRCP/2.0 616 RECOGNITION-COMPLETE 543257 COMPLETE
Channel-Identifier:32AECB23433801@speechrecog
Completion-Cause:000 success
Waveform-URI:<http://web.media.com/session123/audio.wav>;size=342456;duration=25435
Content-Type:application/nlsml+xml
Content-Length:430

<?xml version="1.0"?>
<result xmlns="http://www.ietf.org/xml/ns/mrcpv2"
       xmlns:ex="http://www.example.com/example"
       grammar="session:request1@form-level.store">
   <interpretation>
       <instance name="Person">
           <ex:Person>
               <ex:Name> Andre Roy </ex:Name>
           </ex:Person>
       </instance>
       <input>   may I speak to Andre Roy </input>
   </interpretation>
</result>