MRCP/2.0 732 SPEAK 543257
Channel-Identifier:32AECB23433802@speechsynth
Voice-gender:neutral
Voice-Age:25
Prosody-volume:medium
Content-Type:application/ssml+xml
Content-Length:542

<?xml version="1.0"?>
<speak version="1.0"
	xmlns="http://www.w3.org/2001/10/synthesis"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3.org/2001/10/synthesis
	   http://www.w3.org/TR/speech-synthesis/synthesis.xsd"
	xml:lang="en-US">
	<p>
	 <s>You have 4 new messages.</s>
	 <s>The first is from Stephanie Williams and arrived at
		<break/>
		<say-as interpret-as="vxml:time">0345p</say-as>.
		</s>
	 <s>The subject is
			<prosody rate="-20%">ski trip</prosody>
	 </s>
	</p>
</speak>