top_builddir = ../../..

HEADERS = mailmbox.h mailmbox_types.h
SOURCES = mailmbox_parse.c mailmbox.c mailmbox_types.c
TARGET = libmbox
INCLUDES = -I$(srcdir)/data-types -I../imf

include $(top_builddir)/Rules
