name: Windows

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [master, release]
jobs:
  x64:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download yasm.exe
      run: |
        curl -o libs\win32\ffmpeg\yasm.exe https://files.freeswitch.org/downloads/win64/yasm-1.3.0.87.g121a.exe
        copy libs\win32\ffmpeg\yasm.exe libs\win32\libvpx\yasm.exe

    - name: Verify and Run yasm.exe
      run: |
        if exist libs\win32\ffmpeg\yasm.exe (
          libs\win32\ffmpeg\yasm.exe --version
        ) else (
          echo ERROR: yasm.exe not found!
          exit 1
        )
      shell: cmd

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild Freeswitch.2017.sln -t:build -verbosity:minimal -property:Configuration=Release -property:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSI Package
        path: D:\a\freeswitch\freeswitch\x64\*.msi
      if: contains(github.event.pull_request.title, ':upload-artifacts') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/v1.10'
